
management:
  health:
    defaults:
      enabled: false
    db:
      enabled: true

    
spring:
  application.name: toyrobot
  profiles:
    active: development

---

spring:
  profiles: development

  board:
    x.dimension: 5
    y.dimension: 5

server:
  port: 8080