spring:
  application.name: toyrobot
  profiles:
    active: development

---

spring:
  profiles: development

  board:
    x.dimension: 5
    y.dimension: 5

server:
  port: 8080
  servlet.contextPath: /toyrobot


---

spring:
  profiles: test

  board:
    x.dimension: 5
    y.dimension: 5

server:
  port: 8080
  servlet.contextPath: /toyrobot